name: Deploying the VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_image:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SAM_HOST }}
          username: ${{ secrets.VPS_SAM_USERNAME }}
          password: ${{ secrets.VPS_SAM_PASSWORD }}
          # key: ${{ secrets.VPS_SAM_SSH_PRIVATE_KEY }}
          # fingerprint: ${{ secrets.VPS_SAM_FINGERPRINT }}
          port: 22
          script: |
            # ls -l
            cd /home/site/wnx
            git pull origin main
