# name: Deploy to VPS

# on:
#   push:
#     branches: [main]
#   workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Setup SSH
#         uses: webfactory/ssh-agent@v0.5.3
#         with:
#           ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

#       - name: Deploy to VPS
#         run: |
#           ssh -o StrictHostKeyChecking=no wnx@${{ secrets.VPS_HOST }} 'bash -s' < deploy_script.sh

name: Deploying the application

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_image:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SAM_HOST }}
          username: ${{ secrets.VPS_SAM_USERNAME }}
          # password: ${{ secrets.VPS_SAM_PASSWORD }}
          key: ${{ secrets.VPS_SAM_SSH_PRIVATE_KEY }}
          # fingerprint: ${{ secrets.VPS_SAM_FINGERPRINT }}
          port: 22
          script: |
            # ls -l
            cd /home/site/wnx
            git pull origin main
